DATA:
  DATA_PATH: "/zhouyafei/image_recog_data/ImageNet21k/"
  # multi dataset
  DATA_ROOTS: [
    "/zhouyafei/image_recog_data/AliProducts/",
    "/zhouyafei/image_recog_data/ImageNet21k/",
  ]
  DATA_PATHS: [
    "/zhouyafei/workspace/goods/data/train_0_49980.txt",
    "/zhouyafei/image_recog_data/ImageNet21k/labels/train.txt",
  ]
  VAL:
    CLASSFIER_INDEXS: [0, 1] # The index in _C.DATA.DATA_ROOTS，start 0
    DATA_ROOTS: [
      "/zhouyafei/image_recog_data/AliProducts/",
      "/zhouyafei/image_recog_data/ImageNet21k/",
    ]
    DATA_PATHS: [
      "/zhouyafei/image_recog_data/AliProducts/val_0_49980.txt",
      "/zhouyafei/image_recog_data/ImageNet21k/labels/val.same.txt",
    ]
    SINGLE_DATA_ROOTS: [
      "/zhouyafei/image_recog_data/ImageNet21k/",
    ]
    SINGLE_DATA_PATHS: [
      "/zhouyafei/image_recog_data/ImageNet21k/labels/val.same.txt",
    ]
MODEL:
  TYPE: swin
  NAME: swin_base_patch4_window7_224_22k_ali
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 7
TRAIN:
  EPOCHS: 15
  WARMUP_EPOCHS: 0
  WEIGHT_DECAY: 1e-8
  BASE_LR: 2e-05
  WARMUP_LR: 2e-08
  MIN_LR: 2e-07
  FREEZE_EPOCH: 2
TAG: "20220428a"
