DATA:
  DATASET: imagenet22K
MODEL:
  TYPE: swin
  NAME: swin_base_patch4_window7_224_22k
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 7
TRAIN:
  EPOCHS: 90
  #  WARMUP_EPOCHS: 5
  WARMUP_EPOCHS: 6
  WEIGHT_DECAY: 0.05
  #  BASE_LR: 1.25e-4 # 4096 batch-size
  BASE_LR: 5e-5 # 4096 batch-size
  #  WARMUP_LR: 1.25e-7
  WARMUP_LR: 5e-8
  #  MIN_LR: 1.25e-6
  MIN_LR: 5e-7
  CLIP_GRAD: 0.5
TAG: "20220414a"